version: '3'

services:
  tensorflow:
    image: deeplearningzerotoall/tensorflow
    container_name: tensorflow
    command: sh ./run_jupyter_docker.sh
    volumes:
      - ./:/workspace/
    ports:
      - "8888:8888"
      - "6006:6006"

